version: 0.0
os: linux

files:
  - source:  /
    destination: /opt/testapp
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/testapp
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: root